spring:
  application:
    name: tournament
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${TOURNAMENT_DB_USERNAME}
    password: ${TOURNAMENT_DB_PASSWORD}
    url: ${TOURNAMENT_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    user: ${TOURNAMENT_DB_USERNAME}
    password: ${TOURNAMENT_DB_PASSWORD}
    url: ${TOURNAMENT_DB_URL}
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
logging:
  level:
    org.springframework.boot.actuate.endpoint.web.servlet: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR