spring:
  application:
    name: ticket
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${TOURNAMENT_DB_USERNAME}
    password: ${TOURNAMENT_DB_PASSWORD}
    url: ${TOURNAMENT_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    user: ${TOURNAMENT_DB_USERNAME}
    password: ${TOURNAMENT_DB_PASSWORD}
    url: ${TOURNAMENT_DB_URL}
    baseline-on-migrate: true
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus